version: '3'

services:
  nginx:
    container_name: suhail-nginx
    image: suhail-nginx
    build:
      context: .
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    restart: always
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/acme-challenge:/tmp/acme-challenge
    networks:
      - suhail_network
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  certbot:
    container_name: suhail-certbot
    image: certbot/certbot:latest
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme-challenge:/tmp/acme-challenge"
    depends_on:
      - nginx
    entrypoint: ""
    command: sh -c "certbot certonly --webroot -w /tmp/acme-challenge -d ${DOMAIN_NAME} --text --agree-tos --non-interactive --email ${ADMIN_EMAIL} --rsa-key-size ${RSA_KEY_SIZE} --verbose"
    networks:
      - suhail_network

networks:
  suhail_network:
    external: true
    name: ${NETWORK_NAME}
